{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: pgbouncer-secret
    suite: pachyderm
  name: pgbouncer-secret
  namespace: {{ .Release.Namespace }}
data:
  DB_PASSWORD: {{ .Values.global.postgresql.postgresqlPassword | toString | b64enc | quote }}
