{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.console.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: console-secret
    suite: pachyderm
  name: console-secret
  namespace: {{ .Release.Namespace }}
data:
  OAUTH_CLIENT_SECRET: {{ include "pachyderm.consoleSecret" . | toString | b64enc | quote }}
{{- end }}
