{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-config
  namespace: {{ .Release.Namespace }}
stringData:
{{- if eq .Values.deployTarget "LOCAL" }}
  # authConfig is the configuration for pachd as an OIDC client
  authConfig: |
    client_id: pachd 
    client_secret: notsecret
    issuer: http://localhost:30658/
    localhost_issuer: true
    require_email_verified: false
    redirect_uri: http://pachd:1657/authorization-code/callback
    scopes:
    - email
    - profile
    - groups
    - openid 
{{- end }}

  # clusterRoleBindings is a set of user -> role mappings to apply
  clusterRoleBindings: |
    robot:test:
    - repoReader

  # enterpriseClusters is the set of pachds covered by license service 
  enterpriseClusters: |
    - address: grpc://localhost:1650
      id: localhost
      secret: secret
      user_address: grpc://localhost:30650
      cluster_deployment_id: {{ include "pachyderm.dashSecret" . }}

  # enterpiseConfig points the pachd to a license service (in this case itself)
{{- if eq .Values.deployTarget "LOCAL" }}
  enterpriseConfig: |
    id: localhost
    license_server: grpc://localhost:1650
    secret: secret
{{- end }}

  # identityServiceConfig configures the OIDC provider
{{- if eq .Values.deployTarget "LOCAL" }}
  identityServiceConfig: |  
    issuer: http://localhost:30658/
    id_token_expiry: 1d
{{- end }}

{{- if eq .Values.deployTarget "LOCAL" }}
  # idps is the set of Identity Providers to support for logging in
  idps: |
    - id: test
      jsonConfig: '{"username": "admin", "password": "password"}'
      name: test
      type: mockPassword
{{- end }}

  license: {{ required "Enterprise license key required" .Values.pachd.enterpriseLicenseKey | quote }}

{{- if eq .Values.deployTarget "LOCAL" }}
  # oidcClients is the set of OIDC clients registered with the OIDC provider
  oidcClients: |
    - id: pachyderm
      name: pachd
      secret: oidcsecret
      redirect_uris:
      - http://pachd:1657/authorization-code/callback
      trusted_peers:
      - dash
{{- end }}

  # rootToken is the auth token used to communicate with the cluster as the root user
  rootToken: {{ default (randAlphaNum 32) .Values.pachd.rootToken | quote }}
