{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: deployment-id-secret
    suite: pachyderm
  name: deployment-id-secret
  namespace: {{ .Release.Namespace }}
data:
  CLUSTER_DEPLOYMENT_ID: {{ include "pachyderm.clusterDeploymentId" . | toString | b64enc | quote }}
